stages:
  - build
  - test

build_job:
  stage: build
  script:
    - echo "Compilation du projet Java"
    - mvn compile

test_job:
  stage: test
  script:
    - echo "Tests unitaires"
    - mvn test
