image: eclipse-temurin:17

stages:
  - build
  - test

before_script:
  - apt-get update && apt-get install -y make

build_job:
  stage: build
  script:
    - echo "Nettoyage et compilation des projets"
    - cd java_intro && make clean && make all
    - cd ../kotlin_intro && make clean && make all

test_job:
  stage: test
  script:
    - echo "Aucun test automatisé défini pour le moment"
    - echo "Étape de test réussie (placeholder)"
